name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16'
      - name: Install
        run: |
          npm --prefix .github ci
      - name: Test
        run: |
          node .github/validate.js
        env:
          HEAD_SHA: ${{ github.event.after }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
